### ISSUE TITLE
Information for charging threshold

### ISSUE THREAD

**Issue by maniacx** [Slimbook-Team/slimbook-qc71-dkms#9]
I was interested in supporting slimbook laptop in Gnome extension **Battery Health Charging** after watching The Linux Experiment youtube channel. On searching I found this repo.

https://extensions.gnome.org/extension/5724/battery-health-charging/

https://github.com/maniacx/Battery-Health-Charging

The extension check the wmi path and loads the settings compatible to the model.
Is the wmi path below correct and available on slimbook? if not what is the correct path?

```
ls /sys/devices/platform/qc71_laptop
```

Also does slimbook accept any values at the below path from 1 to 100? or are there any restrictions?
```
/sys/class/power_supply/BAT0/charge_control_end_threshold
```

**Comment by Lt-Henry** [comment]
Hi! Sorry for this late answer.

Yeah, wmi path is that, thing is, there is only exposed some device specific features/properties, ie: slimbook silent mode
What are you expecting to find there?

Battery control threshold is restricted to [1,100] range from driver side. To be honest, can't say if hardware can override this for safety reasons, I would have to ask it.

**Comment by maniacx** [comment]
>What are you expecting to find there?


Nothing.. the extension support several [make/model](https://maniacx.github.io/Battery-Health-Charging/device-compatibility), and I only use wmi path to distinguish between make/model and load options to change threshold accordingly. So extension only checks for the wmi sys-fs path.
https://github.com/maniacx/Battery-Health-Charging/blob/GNOME45%2B/devices/QC71.js

Since the extension supports poborns qc71_laptop (although nobody has reported it is working or not working.), it should work on slimbook laptops. I just wanted to know if the sysfs paths was correct for detection or anything was changed.

Thanks for the information Henry.
